[icon-theme]
name = "Symbols Icons"

[icon-theme.ui]
"settings" = "icons/gear.svg"
"file" = "icons/document.svg"
"directory.opened" = "icons/folder-open.svg"
"directory.closed" = "icons/folder.svg"

[icon-theme.foldername]
".github" = "icons/github.svg"
".git" = "icons/git.svg"

[icon-theme.filename]
"Dockerfile" = "icons/docker.svg"
"Containerfile" = "icons/docker.svg"

".gitignore" = "icons/git.svg"
".gitattributes" = "icons/git.svg"
"Makefile" = "icons/shell.svg"
"docs" = "icons/folder-docs.svg"
"LICENSE" = "icons/license.svg"

"go.work" = "icons/go.svg"
"go.mod" = "icons/go-mod.svg"

# Rust
"Cargo.lock" = "icons/rust.svg"
"Cargo.toml" = "icons/rust.svg"
".rustfmt.toml" = "icons/rust.svg"
"rustfmt.toml" = "icons/rust.svg"
"rust-toolchain.toml" = "icons/rust.svg"

[icon-theme.extension]
"java" = "icons/java.svg"
"gradle" = "icons/gradle.svg"
"elixir" ="icons/elixir.svg"
"c" = "icons/c.svg"
"cpp" = "icons/cplus.svg"
"cs" = "icons/csharp.svg"
"js" = "icons/js.svg"
"julia" = "icons/julia.svg"
"kotlin" = "icons/kotlin.svg"
"fs" = "icons/fsharp.svg"
"lua" = "icons/lua.svg"
"dart" = "icons/dart.svg"
"angular" = "icons/angular.svg"
"csv" = "icons/csv.svg"
"md" = "icons/markdown.svg"
"toml" = "icons/toml.svg"
"rs" = "icons/rust.svg"
"go" = "icons/go.svg"
"svg" = "icons/svg.svg"
"ps1" = "icons/shell.svg"
"sh" = "icons/shell.svg"
"json" = "icons/brackets-yellow.svg"
"bash" = "icons/shell.svg"
"ico" = "icons/image.svg"
"xml" = "icons/xml.svg"
"rtf" = "icons/text.svg"
"wxs" = "icons/xml.svg"
"plist" = "icons/xml.svg"
"png" = "icons/image.svg"
"yml" = "icons/yaml.svg"
"yaml" = "icons/yaml.svg"
"txt" = "icons/text.svg"
"py" = "icons/python.svg"
"spec" = "icons/xml.svg"
"pl" = "icons/perl.svg"
"r" = "icons/r.svg"
"tsx" = "icons/react-ts.svg"
"jsx" = "icons/react.svg"
"rb" = "icons/ruby.svg"
"sass" = "icons/sass.svg"
"svt" = "icons/sbt.svg"
"svelte" = "icons/svelte.svg"
"swift" = "icons/swift.svg"
"ts" = "icons/ts.svg"
"vue" = "icons/vue.svg"